image: registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7

stages:
- cache
- build
- test
- deploy_to_nexus
- deploy_to_dev

variables:
  GROUPID: org.jnd.microservices
  ARTIFACTID: inventory
  VERSION: 0.0.1-SNAPSHOT
  PACKAGING: jar

  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  OPENSHIFT_SERVER: openshift.default.svc.cluster.local
  OPENSHIFT_DOMAIN: apps.ocp.datr.eu
  OPENSHIFT_TOKEN: icSXVM9_eJqAPXDEJSFUSsuHl2hU7eSyZEhv01UNRgQ
  OPENSHIFT_PROJECT: amazin-gitlab

cache:
  key: "amazin-cache"
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

deploy_to_nexus:
  stage: deploy_to_nexus
  script:
  - mvn $MAVEN_CLI_OPTS deploy


.deploy: &deploy
  before_script:
  - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
  - oc project "$OPENSHIFT_PROJECT"
  script:
  - "mvn -B -q -s settings.xml dependency:copy -DstripVersion=true -Dartifact=$GROUPID:$ARTIFACTID:$VERSION:$PACKAGING -DoutputDirectory=."

  - rm -rf .m2/repository/org/jnd/microservices/inventory/0.0.1-SNAPSHOT

  - cp $(find . -type f -name $ARTIFACTID-*.$PACKAGING) $ARTIFACTID-$VERSION.$PACKAGING

  - oc start-build $APP --from-file=$ARTIFACTID-$VERSION.$PACKAGING --follow

  - oc rollout pause dc/$ARTIFACTID 2>/dev/null

  - oc set image dc/$ARTIFACTID $ARTIFACTID=docker-registry.default.svc:5000/$OPENSHIFT_PROJECT/$ARTIFACTID:latest

  - oc delete configmap $ARTIFACTID-config --ignore-not-found=true

  - oc create configmap $ARTIFACTID-config --from-file=src/main/resources/config.dev.properties

  - oc rollout resume dc/$ARTIFACTID

  - oc rollout latest dc/$ARTIFACTID

deploy_to_dev:
  <<: *deploy
  stage: deploy_to_dev
  variables:
    APP: inventory
    APP_HOST: $ARTIFACTID-$OPENSHIFT_PROJECT.$OPENSHIFT_DOMAIN
  environment:
    name: staging
    url: http://$ARTIFACTID-$OPENSHIFT_PROJECT.$OPENSHIFT_DOMAIN
  only:
  - master

