image: registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7

stages:
- cache
- build
- test
- nexus
- deploy_to_dev

variables:
  APP: inventory
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  OPENSHIFT_SERVER: openshift.default.svc.cluster.local
  OPENSHIFT_DOMAIN: apps.ocp.datr.eu
  OPENSHIFT_TOKEN: icSXVM9_eJqAPXDEJSFUSsuHl2hU7eSyZEhv01UNRgQ
  OPENSHIFT_PROJECT: amazin-gitlab

cache:
  key: "amazin-cache"
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

nexus:
  stage: nexus
  script:
  - mvn $MAVEN_CLI_OPTS deploy

.deploy: &deploy
  before_script:
  - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
  - oc project "$OPENSHIFT_PROJECT"
  script:
  - oc delete all -l app=$APP 2> /dev/null
  - oc new-app . --name=$APP --strategy=docker
  - sleep 3s && oc start-build $APP --from-dir=. --follow
  - oc expose service $APP --hostname=$APP_HOST


deploy_to_dev:
  <<: *deploy
  stage: deploy_to_dev
  variables:
    APP: inventory
    APP_HOST: $APP-$OPENSHIFT_PROJECT.$OPENSHIFT_DOMAIN
  environment:
    name: staging
    url: http://$APP-$OPENSHIFT_PROJECT.$OPENSHIFT_DOMAIN
  only:
  - master

